name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: nuget-${{ runner.os }}-6.0.x
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      env:
        PR_NUMBER: ${{ github.event.number || 0 }}
      run: |
        echo $Env:PR_NUMBER
        $Env:SEMVER = $Env:GITHUB_REF_NAME.SubString(1)
        echo $Env:SEMVER
        $Env:VERSION = "$Env:SEMVER.$Env:PR_NUMBER"
        echo $Env:VERSION
        dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o output -p:PublishDir=output -p:Version=$Env:VERSION

    - name: Zip
      run: Compress-Archive -Path output\7za.exe, output\NMSSaveDataUtil.exe -DestinationPath "NMSSaveDataUtil-${Env:GITHUB_REF_NAME}-win-x64.zip"

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: NMSSaveDataUtil-${{ github.ref_name }}-win-x64.zip
