name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    steps:
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: nuget-${{ runner.os }}-${{ matrix.dotnet-version }}
        restore-keys: |
          nuget-${{ runner.os }}-

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish
      env:
        PR_NUMBER: ${{ github.event.number || 0 }}
      run: |
        echo $Env:PR_NUMBER
        $Env:SEMVER = $Env:GITHUB_REF_NAME.SubString(1)
        echo $Env:SEMVER
        $Env:VERSION = "$Env:SEMVER.$Env:PR_NUMBER"
        echo $Env:VERSION
        dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o output -p:PublishDir=output -p:Version=$Env:VERSION

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: NMSSaveDataUtil-${{ env.GITHUB_REF_NAME }}-win-x64
        path: |
          output/NMSSaveDataUtil.exe
          output/7za.exe
        retention-days: 1

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: output/*
