name: .NET Core Windows 64bit Binary

on:
  push:
    branches:
      - actions-ignore

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      env:
        PR_NUMBER: ${{ github.event.number || 0 }}
      run: dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o output -p:PublishDir=output -p:Version=1.0.0.$Env:PR_NUMBER

    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: win-x64-binary
        path: |
          output/NMSSaveDataUtil.exe
          output/7za.exe
        retention-days: 1
